-- MySQL Script generated by MySQL Workbench
-- Fri Nov 18 17:06:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tax
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tax` ;

-- -----------------------------------------------------
-- Schema tax
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tax` DEFAULT CHARACTER SET utf8 ;
USE `tax` ;

-- -----------------------------------------------------
-- Table `tax`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax`.`user` ;

CREATE TABLE IF NOT EXISTS `tax`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NULL,
  `date_of_birth` DATE NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `tax`.`tax_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax`.`tax_type` ;

CREATE TABLE IF NOT EXISTS `tax`.`tax_type` (
  `id` INT NOT NULL,
  `tax_name` VARCHAR(255) NOT NULL,
  `tax_multiplier` DECIMAL(3,3) NOT NULL,
  `tax_description` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `tax`.`user_tax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax`.`user_tax` ;

CREATE TABLE IF NOT EXISTS `tax`.`user_tax` (
  `id_payment` INT NOT NULL,
  `user_id` INT NOT NULL,
  `tax_id` INT NOT NULL,
  `value` DECIMAL(10,5) NOT NULL,
  `tax_amount` DECIMAL(10,5) NOT NULL,
  `payment_date` DATE NOT NULL,
  PRIMARY KEY (`id_payment`),
  INDEX `fk_user_tax_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_tax_tax1_idx` (`tax_id` ASC) VISIBLE,
  UNIQUE INDEX `id_payment_UNIQUE` (`id_payment` ASC) VISIBLE,
  CONSTRAINT `fk_user_tax_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `tax`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_tax_tax1`
    FOREIGN KEY (`tax_id`)
    REFERENCES `tax`.`tax_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
